USE CATAPI_DATABASE
CREATE TABLE TL_LGTB_RACAGATOS_RACA
(
   ID_RACA_CD_RACAGATOS INT NOT NULL PRIMARY KEY  AUTO_INCREMENT, 
    RACA_TX_IMPERIAL VARCHAR(200)  NULL,
    RACA_TX_METRIC VARCHAR(200)  NULL,
    RACA_TX_ID VARCHAR(20)  NULL ,
    RACA_TX_NAME VARCHAR(200)  NULL,
    RACA_TX_CFAURL VARCHAR(200)  NULL,
    RACA_TX_VETSTREETURL VARCHAR(200)  NULL,
    RACA_TX_TEMPERAMENT VARCHAR(200)  NULL,
    RACA_TX_ORIGEN VARCHAR(200)  NULL,
    RACA_TX_COUNTRYCODE VARCHAR(200)  NULL,
    RACA_TX_DESCRIPTION VARCHAR(2000)  NULL,
    RACA_TX_LIFESPAN VARCHAR(200)  NULL,
    RACA_TX_INDOOR VARCHAR(200)  NULL,
    RACA_TX_LAP VARCHAR(200)  NULL,
    RACA_TX_ALTNAMES VARCHAR(200)  NULL,
    RACA_TX_ADAPTABILITY VARCHAR(200)  NULL,
    RACA_TX_CHILDFRIENDLY VARCHAR(200)  NULL,
    RACA_TX_DOGFRIENDLY VARCHAR(200)  NULL,
    RACA_TX_ENERGYLEVEL VARCHAR(200)  NULL,
    RACA_TX_GROOMING VARCHAR(200)  NULL,
    RACA_TX_HEALTHISSUES VARCHAR(200)  NULL,
    RACA_TX_INTELLIGENCE VARCHAR(200)  NULL,
    RACA_TX_SHEDDINGLEVEL VARCHAR(200)  NULL,
    RACA_TX_SOCIALNEEDS VARCHAR(200)  NULL,
    RACA_TX_STANGER_FRIENDLY VARCHAR(200)  NULL,
    RACA_TX_VOCALISTAION VARCHAR(200)  NULL,
    RACA_TX_EXPERIMENTAL VARCHAR(200)  NULL,
    RACA_TX_HAIRLESS VARCHAR(200)  NULL,
    RACA_TX_NATURAL VARCHAR(200)  NULL,
    RACA_TX_RARE VARCHAR(200)  NULL,
    RACA_TX_REX VARCHAR(200)  NULL,
    RACA_TX_SUPPRESSEDTAIL VARCHAR(200)  NULL,
    RACA_TX_SHORTLEGS VARCHAR(200)  NULL,
    RACA_TX_WIKIPEDIAURL VARCHAR(200)  NULL,
    RACA_TX_HYPOALLERGENIC VARCHAR(200)  NULL,
    RACA_TX_BIDABILITY VARCHAR(200)  NULL,
    RACA_DH_DATAREGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP
    
    );
    
    
 USE CATAPI_DATABASE       
 CREATE TABLE TL_LGTB_CATEGORIAIMAGEM_CAIM (
    
 	ID_CAIM_CD_CATEGORIAIMAGEM INT NOT NULL PRIMARY KEY AUTO_INCREMENT ,
	CAIM_ID_EXTERNO INT NOT NULL,
	CAIM_TX_NAME VARCHAR(20),
	CAIM_DH_DATAREGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP
		    );
    
    
CREATE TABLE TL_LGTB_IMAGEMGATO_IMGA (
    
 	ID_IMGA_CD_IMAGEMGATO INT NOT NULL PRIMARY KEY  AUTO_INCREMENT, 
    RACA_TX_ID VARCHAR(20),
    IMGA_TX_URLIMAGE VARCHAR(2000),
    IMGA_TX_WIDTH VARCHAR(20),
    IMGA_TX_HEIGHT VARCHAR(20),
    IMGA_DH_DATAREGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    ID_CAIM_CD_CATEGORIAIMAGEM INT,
    ID_RACA_CD_RACAGATOS INT
    );
 
CREATE TABLE TL_NGTB_LOGINCATAPI_LOGI (
	 	ID_LOGI_CD_LOGINCATPAI INT NOT NULL PRIMARY KEY  AUTO_INCREMENT, 
        LOGI_TX_USUARIO VARCHAR(20),
        LOGI_TX_SENHA VARCHAR(20),
        LOGI_DH_DATAREGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO TL_NGTB_LOGINCATAPI_LOGI (LOGI_TX_USUARIO,LOGI_TX_SENHA) VALUES ('catapirest','catapirest');
    
CREATE TABLE ES_NGTB_CONTROLELOG_COLO (
   ID_COLO_CD_CONTROLELOG INT NOT NULL PRIMARY KEY  AUTO_INCREMENT,  	
   COLO_TX_LOGENTRADA VARCHAR(2000),	
   LOGI_DH_DATAREGISTROLOGENTRADA DATETIME,
   COLO_TX_LOGSAIDA VARCHAR(2000),
   COLO_DH_DATAREGISTROLOGSAIDA DATETIME,
   COLO_TX_ERRO VARCHAR (200)
);


ALTER TABLE TL_LGTB_IMAGEMGATO_IMGA ADD CONSTRAINT FK_IMAGEMGATOCATEGORIA FOREIGN KEY(ID_CAIM_CD_CATEGORIAIMAGEM) REFERENCES TL_LGTB_CATEGORIAIMAGEM_CAIM (ID_CAIM_CD_CATEGORIAIMAGEM);
ALTER TABLE TL_LGTB_IMAGEMGATO_IMGA ADD CONSTRAINT FK_IMAGEMGATORACA FOREIGN KEY(ID_RACA_CD_RACAGATOS) REFERENCES TL_LGTB_RACAGATOS_RACA (ID_RACA_CD_RACAGATOS);
    


