package br.com.catpi.dao;

public class ImagemGatoRacaQueryDao {

	public static final String  QUERY_INSERT_IMAGEMRACAGATO = " INSERT INTO TL_LGTB_IMAGEMGATO_IMGA (RACA_TX_ID,IMGA_TX_URLIMAGE,IMGA_TX_WIDTH,IMGA_TX_HEIGHT,ID_CAIM_CD_CATEGORIAIMAGEM,ID_RACA_CD_RACAGATOS) VALUES (?,?,?,?,?,?)";
	public static final String QUERY_CONSULTA_POR_ID_URL = " SELECT * FROM TL_LGTB_IMAGEMGATO_IMGA WHERE IMGA_TX_URLIMAGE = ? " ; 
	
}
	
