package br.com.catpi.dao;

public class RacaoQueryDao {
	
	
	public static final String RACA_INSERT = " INSERT INTO TL_LGTB_RACAGATOS_RACA "
			+ "("
			+ " RACA_TX_IMPERIAL,"
			+ " RACA_TX_METRIC,"
			+ " RACA_TX_ID,"
			+ " RACA_TX_NAME,"
			+ " RACA_TX_CFAURL,"
			+ " RACA_TX_VETSTREETURL,"
			+ " RACA_TX_TEMPERAMENT, "
			+ "	RACA_TX_ORIGEN,"
			+ "	RACA_TX_COUNTRYCODE, "
			+ " RACA_TX_DESCRIPTION,"
			+ " RACA_TX_LIFESPAN,"
			+ " RACA_TX_INDOOR,"
			+ " RACA_TX_LAP, "
			+ " RACA_TX_ALTNAMES,"
			+ " RACA_TX_ADAPTABILITY, "
			+ " RACA_TX_CHILDFRIENDLY,"
			+ " RACA_TX_DOGFRIENDLY,"
			+ " RACA_TX_ENERGYLEVEL,"
			+ " RACA_TX_GROOMING,"
			+ " RACA_TX_HEALTHISSUES,"
			+ " RACA_TX_INTELLIGENCE,"
			+ " RACA_TX_SHEDDINGLEVEL,"
			+ " RACA_TX_SOCIALNEEDS,"
			+ " RACA_TX_STANGER_FRIENDLY,"
			+ " RACA_TX_VOCALISTAION,"
			+ " RACA_TX_EXPERIMENTAL, "
			+ " RACA_TX_HAIRLESS, "
			+ " RACA_TX_NATURAL,"
			+ " RACA_TX_RARE, "
			+ " RACA_TX_REX,"
			+ " RACA_TX_SUPPRESSEDTAIL,"
			+ " RACA_TX_SHORTLEGS,"
			+ " RACA_TX_WIKIPEDIAURL,"
			+ " RACA_TX_HYPOALLERGENIC, "
			+ " RACA_TX_BIDABILITY  ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)  ";

	public static final String QUERY_CONSULTA_POR_ID_RACA = "SELECT * FROM  TL_LGTB_RACAGATOS_RACA WHERE  RACA_TX_ID = ? " ;
	
	public static final String QUERY_CONSULTA_TODAS_RACAS = " SELECT ID_RACA_CD_RACAGATOS,RACA_TX_ID,RACA_TX_NAME,RACA_TX_TEMPERAMENT,RACA_TX_ORIGEN,RACA_TX_DESCRIPTION   FROM  TL_LGTB_RACAGATOS_RACA "; 
	public static final String QUERY_CONSULTA_LISTAR_INFORMACAO_RACA = " SELECT ID_RACA_CD_RACAGATOS,RACA_TX_ID,RACA_TX_NAME,RACA_TX_TEMPERAMENT,RACA_TX_ORIGEN,RACA_TX_DESCRIPTION   FROM  TL_LGTB_RACAGATOS_RACA  WHERE  RACA_TX_ID = ? "; 
	public static final String QUERY_CONSULTA_LISTAR_INFORMACAO_TEMPERAMENTO = " SELECT ID_RACA_CD_RACAGATOS,RACA_TX_ID,RACA_TX_NAME,RACA_TX_TEMPERAMENT,RACA_TX_ORIGEN,RACA_TX_DESCRIPTION   FROM  TL_LGTB_RACAGATOS_RACA  WHERE  RACA_TX_TEMPERAMENT LIKE ?"; 
	public static final String QUERY_CONSULTA_LISTAR_INFORMACAO_ORIGEM = " SELECT ID_RACA_CD_RACAGATOS,RACA_TX_ID,RACA_TX_NAME,RACA_TX_TEMPERAMENT,RACA_TX_ORIGEN,RACA_TX_DESCRIPTION   FROM  TL_LGTB_RACAGATOS_RACA  WHERE  RACA_TX_ORIGEN = ?"; 





}
